// Generated by CoffeeScript 1.7.1
(function() {
  var app, compile, express, http, nib, partials, path, routes, stylus, user;

  express = require('express');

  routes = require('./routes');

  user = require('./routes/user');

  http = require('http');

  path = require('path');

  partials = require('express-partials');

  nib = require('nib');

  stylus = require('stylus');

  app = express();

  app.engine('hamlc', require('haml-coffee').__express);

  app.use(partials());

  compile = function(str, path) {
    return stylus(str).set('filename', path).set('compress', true).use(nib());
  };

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'hamlc');
    app.set('layout', 'layout');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser('your secret here'));
    app.use(express.session());
    app.use(app.router);
    app.use(stylus.middleware({
      src: __dirname + '/public',
      compile: compile
    }));
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  app.get('/users', user.list);

  http.createServer(app).listen(app.get('port'), function() {
    return console.log("Express server listening on port " + app.get('port'));
  });

}).call(this);
